# renew_before_expiry = 30 days
version = 3.3.0
archive_dir = /etc/letsencrypt/archive/byteon.richardlander.cornwall.sch.uk
cert = /etc/letsencrypt/live/byteon.richardlander.cornwall.sch.uk/cert.pem
privkey = /etc/letsencrypt/live/byteon.richardlander.cornwall.sch.uk/privkey.pem
chain = /etc/letsencrypt/live/byteon.richardlander.cornwall.sch.uk/chain.pem
fullchain = /etc/letsencrypt/live/byteon.richardlander.cornwall.sch.uk/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = ea1bef952039dd502cd84179344287c3
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
webroot_path = /var/www/certbot,
[[webroot_map]]
byteon.richardlander.cornwall.sch.uk = /var/www/certbot
